title: Rockfic.com Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://www.rockfic.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#ff2e2e"
  systems:
    - name: Database
      category: Systems
    - name: Website
      category: Systems
    - name: Forum
      category: Systems
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#F03A5F"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#ffdd57"
  notice: "#7444a2"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#48c774"
  categories: []
  description: check back here periodically to see if things are working or not!
  enableCustomHTML: true
  useLargeHeaderDesign: true
